export default {
    Guard1: {
        Health: 10,
        Damage: 2,
        Cooldown: 1,
        Range: 20,
    },
    Guard2: {
        Health: 10,
        Damage: 2,
        Cooldown: 0.5,
        Range: 20,
    },
    Guard3: {
        Health: 50,
        Damage: 2,
        Cooldown: 0.2,
        Range: 25,
    },
    GoldenGuard1: {
        Health: 10,
        Damage: 2,
        Cooldown: 0.6,
        Range: 20,
    },
    GoldenGuard2: {
        Health: 10,
        Damage: 3,
        Cooldown: 0.3,
        Range: 20,
    },
    GoldenGuard3: {
        Health: 50,
        Damage: 4,
        Cooldown: 0.15,
        Range: 25,
    },
    Sentry1: {
        Health: 20,
        Damage: 1,
        Cooldown: 0.5,
        Range: 16,
        Lifespan: 16,
        Scrap: 16,
    },
    Sentry2: {
        Health: 40,
        Damage: 2,
        Cooldown: 0.25,
        Range: 20,
        Lifespan: 30,
        Scrap: 20,
    },
    Sentry3: {
        Health: 60,
        Damage: 5,
        Cooldown: 0.16,
        Range: 20,
        Lifespan: 45,
        Scrap: 50,
    },
    Sentry4: {
        Health: 120,
        Damage: 12,
        Cooldown: 0.12,
        Range: 22,
        Lifespan: 60,
        Scrap: 100,
        ExplosionDamage: 15,
        TimeBetweenMissiles: 4,
        MissileAmount: 2,
        ExplosionRadius: 5,
    },
    Humvee: {
        Health: 25,
        Damage: 0,
        Cooldown: 0.2,
        Range: 5,
    },
    ['Humvee 2']: {
        Health: 60,
        Damage: 0,
        Cooldown: 0.2,
        Range: 5,
    },
    ['Humvee 3']: {
        Health: 60,
        Damage: 3,
        Cooldown: 0.2,
        Range: 30,
    },
    Tank: {
        Health: 400,
        Damage: 6,
        Cooldown: 0.2,
        Range: 30,
        ExplosionDamage: 25,
        TimeBetweenMissiles: 3,
    },
    ['Railgun Tank']: {
        Health: 1200,
        Damage: 16,
        Cooldown: 0.2,
        Range: 30,
        ExplosionDamage: 60,
        TimeBetweenMissiles: 3,
    },
    Mark1: {
        Health: 400,
        Damage: 8,
        Cooldown: 0.2,
        Range: 30,
    },
    Mark1Rocket: {
        Health: 400,
        Damage: 8,
        Cooldown: 0.2,
        Range: 30,
        ExplosionDamage: 8,
        TimeBetweenMissiles: 5,
    },
    Mark2: {
        Health: 750,
        Damage: 12,
        Cooldown: 0.15,
        Range: 25,
        ExplosionDamage: 8,
        TimeBetweenMissiles: 5,
    },
    Mark3: {
        Health: 1200,
        Damage: 10,
        Cooldown: 0.08,
        Range: 25,
        ExplosionDamage: 8,
        TimeBetweenMissiles: 3,
    },
    Mark4: {
        Health: 2000,
        Damage: 10,
        Cooldown: 0.05,
        Range: 100,
        ExplosionDamage: 8,
        TimeBetweenMissiles: 3,
        MissileAmount: 4,
    },
    Mark5: {
        Health: 5000,
        Damage: 20,
        Cooldown: 0.05,
        Range: 100,
        ExplosionDamage: 8,
        TimeBetweenMissiles: 3,
        MissileAmount: 4,
    },
};
