export default {
    Skeleton: {
        Health: 30,
        Speed: 4,
        Range: 2,
        Detections: {
            Hidden: false,
        },
        Attributes: {},
    },
    'Sword Skeleton': {
        Health: 30,
        Speed: 4,
        Range: 6,
        Cooldown: 0.8,
        Damage: 15,
        Detections: {
            Hidden: true,
        },
        Attributes: {},
    },
    'Skeleton Knight': {
        Health: 100,
        Speed: 3.5,
        Range: 7,
        Cooldown: 0.65,
        Damage: 35,
        Detections: {
            Hidden: true,
        },
        Attributes: {},
    },
    'Hallow Guard': {
        Health: 1250,
        Speed: 1.8,
        Range: 2,
        Detections: {
            Hidden: false,
        },
        Attributes: {},
    },
    'Executioner Skeleton': {
        Health: 3500,
        Speed: 1.8,
        Cooldown: 4,
        Range: 30,
        Damage: 50,
        Detections: {
            Hidden: true,
        },
        Attributes: {},
    },

    Goon1: {
        Range: 14,
        Health: 10,
        Cooldown: 1,
        Damage: 2,
    },
    Goon2: {
        Range: 16,
        Health: 35,
        Cooldown: 0.25,
        Damage: 3,
    },
    Goon3: {
        Range: 18,
        Health: 50,
        Cooldown: 0.18,
        Damage: 4,
    },
    GoldenGoon1: {
        Range: 14,
        Health: 15,
        Cooldown: 1,
        Damage: 2,
    },
    GoldenGoon2: {
        Range: 16,
        Health: 40,
        Cooldown: 0.22,
        Damage: 4,
    },
    GoldenGoon3: {
        Range: 18,
        Health: 65,
        Cooldown: 0.15,
        Damage: 5,
    },
    Sentry1: {
        Range: 18,
        ScrapCost: 16,
        Health: 20,
        Lifetime: 20,
        Speed: 1.25,
        IgnoreCollisionDamage: true,
        Cooldown: 0.45,
        Damage: 1,
        Detections: {
            Hidden: false,
        },
        Attributes: {
            SendTime: 1.25,
            ScrapCost: 16,
            Lifetime: 20,
        },
    },
    Sentry2: {
        Range: 20,
        ScrapCost: 36,
        Health: 40,
        Lifetime: 30,
        Speed: 1.25,
        IgnoreCollisionDamage: true,
        Cooldown: 0.25,
        Damage: 2,
        Detections: {
            Hidden: false,
        },
        Attributes: {
            SendTime: 1.5,
            ScrapCost: 36,
            Lifetime: 30,
        },
    },
    Sentry3: {
        Range: 20,
        ScrapCost: 140,
        Health: 60,
        Lifetime: 45,
        Speed: 1.25,
        IgnoreCollisionDamage: true,
        Cooldown: 0.16,
        Damage: 5,
        Detections: {
            Hidden: false,
        },
        Attributes: {
            SendTime: 1.75,
            ScrapCost: 140,
            Lifetime: 45,
        },
    },
    Sentry4: {
        ExplosionDamage: 33,
        TimeBetweenMissiles: 4,
        MissileAmount: 2,
        Range: 24,
        Health: 120,
        Lifetime: 60,
        Speed: 1.5,
        IgnoreCollisionDamage: true,
        Cooldown: 0.12,
        Damage: 8,
        Detections: {
            Hidden: false,
        },
        Attributes: {
            SendTime: 1.75,
            ScrapCost: 300,
            Lifetime: 60,
        },
    },
    Humvee: {
        Health: 25,
        Damage: 0,
        Cooldown: 0.2,
        Range: 5,
    },
    ['Humvee 2']: {
        Health: 60,
        Damage: 0,
        Cooldown: 0.2,
        Range: 5,
    },
    ['Humvee 3']: {
        Health: 60,
        Damage: 3,
        Cooldown: 0.2,
        Range: 30,
    },
    Tank: {
        Health: 400,
        Damage: 6,
        Cooldown: 0.2,
        Range: 30,
        ExplosionDamage: 25,
        TimeBetweenMissiles: 3,
    },
    ['Railgun Tank']: {
        Health: 1200,
        Damage: 16,
        Cooldown: 0.2,
        Range: 30,
        ExplosionDamage: 60,
        TimeBetweenMissiles: 3,
    },
    Mark1: {
        Health: 400,
        Damage: 8,
        Cooldown: 0.2,
        Range: 30,
    },
    Mark1Rocket: {
        Health: 400,
        Damage: 8,
        Cooldown: 0.2,
        Range: 30,
        ExplosionDamage: 8,
        TimeBetweenMissiles: 5,
    },
    Mark2: {
        Health: 750,
        Damage: 12,
        Cooldown: 0.15,
        Range: 25,
        ExplosionDamage: 8,
        TimeBetweenMissiles: 5,
    },
    Mark3: {
        Health: 1200,
        Damage: 10,
        Cooldown: 0.08,
        Range: 25,
        ExplosionDamage: 8,
        TimeBetweenMissiles: 3,
    },
    Mark4: {
        Health: 2000,
        Damage: 10,
        Cooldown: 0.05,
        Range: 100,
        ExplosionDamage: 8,
        TimeBetweenMissiles: 3,
        MissileAmount: 4,
    },
    Mark5: {
        Health: 5000,
        Damage: 20,
        Cooldown: 0.05,
        Range: 100,
        ExplosionDamage: 8,
        TimeBetweenMissiles: 3,
        MissileAmount: 4,
    },
};
