[[redirects]]
  from = "https://chaoshead.netlify.app/*"
  to = "https://tds-editor.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/misc"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/misc/"
  to = "/"
  status = 301
  force = true
