name: Notify Approved Tower Authors

on:
  push:
    branches: [main, master]
    paths:
      - "db/ApprovedList.js"

jobs:
  notify-users:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: |
          npm install node-fetch@2 form-data

      - name: Detect changes and notify users
        run: node .github/scripts/notify.js
        env:
          WIKI_BASE: "https://tds.fandom.com"
          USER_AGENT: "TDS-Stats-Editor-Bot/1.0"
          FANDOM_SESSION: ${{ secrets.FANDOM_SESSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
