name: Discord Commit Notification

on:
  push:
    branches: main

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get commit and file details
        id: commit
        run: |
          COMMITS_JSON=$(git log --oneline ${{ github.event.before }}..${{ github.event.after }} --pretty=format:'{"sha":"%h","message":"%s","author":"%an","full_message":"%B"}' | jq -s .)
          
          echo "commits_json=$COMMITS_JSON" >> $GITHUB_OUTPUT

      - name: Get changed files count
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          since_last_remote_commit: true

      - name: Send Discord notification
        uses: actions/github-script@v7
        with:
          script: |
            const { sendDiscordNotification } = require('./.github/scripts/webhook.js');
            
            const commits = JSON.parse(process.env.COMMITS_JSON || '[]');
            const fileCount = parseInt(process.env.FILE_COUNT || '0');
            
            await sendDiscordNotification(
              process.env.DISCORD_WEBHOOK_URL,
              commits,
              fileCount
            );
            
            console.log('Discord webhook posted successfully');
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COMMITS_JSON: ${{ steps.commit.outputs.commits_json }}
          FILE_COUNT: ${{ steps.changed-files.outputs.changed_files_count }}