name: Discord Commit Notification

on:
  push:
    branches: main

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get commit and file details
        id: commit
        run: |
          COMMITS_JSON=$(git log --oneline ${{ github.event.before }}..${{ github.event.after }} --format='%h%x00%an%x00%s%x00%B%x00' | jq -R -s 'split("") | map(select(. != "")) as $lines | [range(0; $lines | length; 4) as $i | $lines[$i:$i+4]] | map({sha: .[0], author: .[1], message: .[2], full_message: .[3]}) | .')
    
          echo "commits_json<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS_JSON" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Get changed files count
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          since_last_remote_commit: true

      - name: Send Discord notification
        uses: actions/github-script@v7
        with:
          script: |
            const { sendDiscordNotification } = require('./.github/scripts/webhook.js');

            const commits = JSON.parse(process.env.COMMITS_JSON || '[]');
            const fileCount = parseInt(process.env.FILE_COUNT || '0');

            await sendDiscordNotification(
              process.env.DISCORD_WEBHOOK_URL,
              commits,
              fileCount
            );

            console.log('Discord webhook posted successfully');
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COMMITS_JSON: ${{ steps.commit.outputs.commits_json }}
          FILE_COUNT: ${{ steps.changed-files.outputs.all_changed_files_count }}
